# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Module
      run: go mod download
      
    - name: Generate GRPC
      run: protoc --go_out=. --go-grpc_out=. -I proto proto/*proto
      
    - name: Cleanup Module
      run: go mod tidy
      
    - name: Build
      run: go build pingme.go
